target "Lunchie" do
pod 'MKNetworkKit', :head
pod 'MKNetworkKit+RACExtensions', :head
pod 'NSData+Base64', '~> 1.0.0'
end

target "LunchieTests" do
pod 'MKNetworkKit', :head
pod 'MKNetworkKit+RACExtensions', :head
pod 'NSData+Base64', '~> 1.0.0'
end
