target "Lunchie" do
pod 'MKNetworkKit+RACExtensions', '~> 0.2'
pod 'RSOAuthEngine', '~> 1.0.0'
end

target "LunchieTests" do
pod 'MKNetworkKit+RACExtensions', '~> 0.2'
pod 'RSOAuthEngine', '~> 1.0.0'
end
